#!/usr/bin/perl
use warnings FATAL => 'all';
use strict;
use 5.10.0;

use IO::Handle;

my $CL_H = "/usr/include/CL/cl.h";

unless (-e $CL_H) {
    say "Requires OpenCL Headers";
    say;
    say "  sudo apt-get install opencl-headers";
    say;
    exit(1);
}

my %CODES = ();
my %SEEN  = ();

open my $clh, "<", $CL_H;
while (<$clh>) {
    next unless /^#define\s+(CL_\w+)\s+(-?\d+)/;
    
    unless (defined $SEEN{$2}) {
        $CODES{$1}  = 1;
    }
    
    $SEEN{$2} = 1;
}
close $clh;

open my $ph, ">", "include/cl_perror.h"
    or die "Cannot open output ($!)";
$ph->print(<<"DONE");
#ifndef CL_PERROR_H
#define CL_PERROR_H

#include <CL/cl.h>
#include <stdio.h>

/* This file is automatically generated.
 * Any changes you make here will be lost.
 */
static const char* cl_strerror(int code)
  __attribute__((__unused__));

static const char*
cl_strerror(int code) 
{
    switch (code) {
DONE

for my $symbol (keys %CODES) {
    $ph->print(<<"END");
    case $symbol:
        return "$symbol";
END
}

$ph->print(<<"DONE");
    default:
        return "UNKNOWN_ERROR";
    }
}
  
static void cl_perror(int code)
  __attribute__((__unused__));

static void
cl_perror(int code)
{
    fprintf(stderr, "OpenCL Error: %s\\n", cl_strerror(code));
}

#endif
DONE

close $ph;
